USE PARKS_AND_RECREATION;

SELECT * FROM employee_demographics;
SELECT * FROM employee_salary;

-- GROUPBY

-- CANNOT GROUP BY IF NOT USING AGGREGATE FUNCTIONS OR THE SAME COLUMN IN SELECT AND GROUPBY
SELECT GENDER 
FROM employee_demographics
GROUP BY GENDER;

SELECT AVG(AGE) AS AVG_AGE, GENDER
FROM employee_demographics
GROUP BY GENDER;

SELECT AVG(SALARY) AS SALARY_AVG 
FROM employee_salary
GROUP BY GENDER;

SELECT OCCUPATION, SALARY
FROM employee_salary
GROUP BY OCCUPATION, SALARY;

SELECT MIN(AGE),MAX(AGE),COUNT(AGE), GENDER
FROM employee_demographics
GROUP BY GENDER;

-- ORDER BY SORTS IT BY ASCENDING OR DESCENDING BASED ON THE COLUMN

SELECT AVG(AGE) AS AVG_AGE, GENDER
FROM employee_demographics
GROUP BY GENDER
order by AVG_AGE desc;

-- ORDER BY MULTIPLE COLUMNS, FIRST IT'LL SORT BY 1 COLUMN, THEN IT'LL SORT INSIDE THE SECOND COLUMN

SELECT *
FROM employee_demographics
order by GENDER, AGE DESC;

-- QUERY W COLUMN POSITIONS BY USING THEIR COLUMN NUMBER, STARTS WITH 1 - INFINTIE