-- use a specific schema
use parks_and_recreation;

SELECT * FROM EMPLOYEE_DEMOGRAPHICS;

SELECT FIRST_NAME, AGE , AGE + 10 AS "TEN YEARS LATER" FROM EMPLOYEE_DEMOGRAPHICS;

-- unique finder
SELECT DISTINCT AGE FROM EMPLOYEE_DEMOGRAPHICS;

SELECT DISTINCT FIRST_NAME, AGE FROM EMPLOYEE_DEMOGRAPHICS;


