-- STORED PROCEDURES

CREATE PROCEDURE HIGH_EARNERS()
SELECT * 
FROM employee_salary
WHERE SALARY >50000;

DELIMITER $$
CREATE PROCEDURE HIGH_EARNERS2()
BEGIN
	SELECT * FROM EMPLOYEE_SALARY;
    SELECT * FROM EMPLOYEE_DEMOGRAPHICS;
END $$
DELIMITER ;

CALL HIGH_EARNERS2();

DELIMITER $$
CREATE PROCEDURE HIGH_EARNERS3(employeeid INT)
BEGIN
	SELECT * 
    FROM EMPLOYEE_SALARY
    WHERE
    employee_id = employeeid;
END $$
DELIMITER ;

-- drop procedure if exists HIGH_EARNERS3;

call high_earners3(4)
