-- TRIGGERS AND EVENTS

SELECT * FROM employee_salary;
SELECT * FROM employee_demographics;

DELIMITER $$
CREATE TRIGGER AUTOMATIC_INSERT_IN_DEMOGRAPHIC
	AFTER INSERT ON EMPLOYEE_SALARY
    FOR EACH ROW
BEGIN
	INSERT INTO EMPLOYEE_DEMOGRAPHICS (EMPLOYEE_ID, FIRST_NAME, LAST_NAME)
    VALUES (NEW.EMPLOYEE_ID, NEW.FIRST_NAME, NEW.LAST_NAME);
END $$
DELIMITER ;

INSERT INTO EMPLOYEE_SALARY (EMPLOYEE_ID, FIRST_NAME, LAST_NAME)
VALUES (13, "WARDAH", "TAYYEB");

-- EVENTS: SCHEDULED NOT TRIGGERED.

SELECT * FROM employee_demographics;
DELIMITER $$
CREATE EVENT DELETE_RETIREES
ON SCHEDULE EVERY 30 SECOND
DO
BEGIN
	DELETE
    FROM EMPLOYEE_DEMOGRAPHICS
    WHERE AGE>60;
END $$
DELIMITER ;

SHOW VARIABLES LIKE "event%"