USE PARKS_AND_RECREATION;
SELECT * FROM employee_demographics;
SELECT * FROM employee_salary;

-- HAVING AND -- WHERE

-- SEE THIS CANT BE DONE BECAUSE WHERE DOESN'T WORK WITH AGG FUNCTIONS, BUT HAVING DOES
-- SELECT AVG(AGE) FROM EMPLOYEE_DEMOGRAPHICS WHERE AVG(AGE)>40 group by GENDER;

SELECT GENDER, AVG(AGE)
FROM employee_demographics
GROUP BY GENDER
HAVING AVG(AGE) >40;

-- CAN USE BOTH WHERE AND HAVING TOGETHER TOO

SELECT OCCUPATION, AVG(SALARY)
FROM employee_salary
WHERE OCCUPATION LIKE "%MANAGER%"
GROUP BY OCCUPATION
HAVING AVG(SALARY) < 90000;

-- NORMAL COLUMNS ARE FILTERED WITH WHERE
-- AGG COLUMNS ARE FILTERED WITH HAVING